import { defineConfig } from 'tsdown'

/**
 * `@inkin/schema` 0.1.0 build configuration.
 *
 * This package IS the schema kernel — no React, no CSS, no renderer. Future
 * releases under the `@inkin` scope (e.g. `@inkin/react`, `@inkin/mermaid`)
 * are separate packages with their own builds; each depends on `@inkin/schema`
 * for the canonical Diagram type.
 *
 * Output: `dist/index.{js,cjs,d.ts,d.cts}` plus matching `.map` files.
 * `dist/diagram.schema.json` is generated by scripts/emit-json-schema.mjs
 * after tsdown finishes (not produced by Rolldown itself).
 */
export default defineConfig({
  entry: {
    index: 'src/schema/index.ts',
  },
  format: ['esm', 'cjs'],
  dts: true,
  sourcemap: true,
  clean: true,
  treeshake: true,
  // Framework-agnostic kernel: Node, Bun, Deno, edge runtimes, modern browsers
  // — never assume a single host. Enables more aggressive tree-shaking by skipping
  // Node-specific global assumptions.
  platform: 'neutral',
  // Explicit alignment with tsconfig.json `target: "ES2022"` so bundler and
  // typechecker can never disagree about which syntax/features are safe to emit.
  target: 'es2022',
})
