import { defineConfig } from 'tsdown'

/**
 * inkin 0.1.0 build configuration.
 *
 * Ships ONLY the schema kernel — no React, no CSS, no renderer.
 * `inkin/schema` is the only public subpath export in this release; the bare
 * `inkin` root entry is intentionally absent from package.json's `exports` map
 * and will be added in 0.2.0 pointing at the React `<DiagramStudio>` component.
 * No breaking change between 0.1.0 and 0.2.0.
 *
 * `dist/schema/diagram.schema.json` is generated by scripts/emit-json-schema.mjs
 * after tsdown finishes; not produced by Rolldown itself.
 */
export default defineConfig({
  entry: {
    'schema/index': 'src/schema/index.ts',
  },
  format: ['esm', 'cjs'],
  dts: true,
  sourcemap: true,
  clean: true,
  treeshake: true,
  // Framework-agnostic kernel: Node, Bun, Deno, edge runtimes, modern browsers
  // — never assume a single host. Enables more aggressive tree-shaking by skipping
  // Node-specific global assumptions.
  platform: 'neutral',
  // Explicit alignment with tsconfig.json `target: "ES2022"` so bundler and
  // typechecker can never disagree about which syntax/features are safe to emit.
  target: 'es2022',
  // No React, no CSS Modules in 0.1.0 — those configs land at 0.2.0.
})
